version: 2


jobs:
  build:
    docker:
      - image: circleci/python:3.6

    steps:
      - checkout
      - run: sudo pip install sphinx cloud_sptheme
      - run: sphinx-build -b html -d _build/doctrees content _build/html
      - store_artifacts:
          path: _build/html
          destination: preview
